from __future__ import annotations

from pathlib import Path

import pandas as pd

from .matcher import canonicalize
from .models import Atom, AtomRole

REQUIRED_COLUMNS = {"document_id", "atom_id", "role", "value", "human_verified"}


def load_verified_inventory(path: Path) -> list[Atom]:
    """Load the human-verified Tier-1 inventory used as the sampling frame.

    Semantic atom proposal can be generated by a frozen external tool/model, but
    this public package deliberately requires an explicit human_verified flag for
    experimental inventories.
    """
    df = pd.read_csv(path)
    missing = REQUIRED_COLUMNS - set(df.columns)
    if missing:
        raise ValueError(f"Missing inventory columns: {sorted(missing)}")
    df = df.loc[df["human_verified"].astype(bool)]
    atoms: list[Atom] = []
    for row in df.to_dict(orient="records"):
        role = AtomRole(str(row["role"]))
        atoms.append(
            Atom(
                document_id=str(row["document_id"]),
                atom_id=str(row["atom_id"]),
                role=role,
                value=str(row["value"]),
                canonical_value=canonicalize(str(row["value"]), role.value),
                source_text=str(row.get("source_text")) if row.get("source_text") else None,
                source_start=int(row["source_start"])
                if pd.notna(row.get("source_start"))
                else None,
                source_end=int(row["source_end"]) if pd.notna(row.get("source_end")) else None,
            )
        )
    return atoms
